import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';

import './globals.css';

const workSans = Work_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={workSans.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
