import Attribution from '@/components/common/Attribution';
import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';

import './globals.css';

const workSans = Work_Sans({
  weight: ['400', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'FAQ Accordion',
  description: 'Coded by Jason Luo. Challenge by Frontend Mentor. Generated by Next.js.',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={workSans.className}>
        {children}
        <Attribution />
      </body>
    </html>
  );
};

export default RootLayout;
