import styles from './Attribution.module.css';

const Attribution = () => {
  return (
    <div className={styles.attribution}>
      Coded by{' '}
      <a className={styles.link} href="https://github.com/jasonluo07" target="_blank">
        Jason Luo
      </a>
      . Challenge by{' '}
      <a className={styles.link} href="https://www.frontendmentor.io?ref=challenge" target="_blank">
        Frontend Mentor
      </a>
      . Generated by Next.js.
    </div>
  );
};

export default Attribution;
